name: Global On Branch Delete Workflow
on: 
  workflow_call:
    inputs:
      branch:
        description: 'The branch that is being deleted'
        required: true
        type: string
jobs:
  Run_Terraform:
    runs-on:
      - codebuild-github_project-${{ github.run_id }}-${{ github.run_attempt }}
      - image:arm-3.0
      - instance-size:small
    environment: dev
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with: 
          role-to-assume: arn:aws:iam::874500785305:role/codebuild-service-role
          role-session-name: AssumeRoleSession
          aws-region: us-east-1
      - name: STS Get Caller Identity
        run: aws sts get-caller-identity
      - name: Terraform Init
        run: terraform -chdir=./terraform init --backend-config=config/dev.config 
      - name: Terraform Workspace Select
        run: terraform -chdir=./terraform workspace select ${{ inputs.branch }} || terraform -chdir=./terraform workspace new ${{ inputs.branch }}
      - name: Terraform  Destroy
        run: terraform -chdir=./terraform destroy -auto-approve
