name: Global On Push Workflow
on: 
  workflow_call:
    inputs:
      branch:
        description: 'The branch that is being deployed'
        required: true
        type: string
      repository:
        description: 'The repository that is being deployed'
        required: true
        type: string
jobs:
  Build_Image_Run_Terraform:
    runs-on:
      - codebuild-github_project-${{ github.run_id }}-${{ github.run_attempt }}
      - image:arm-3.0
      - instance-size:small
    environment: dev
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with: 
          role-to-assume: arn:aws:iam::874500785305:role/codebuild-service-role
          role-session-name: AssumeRoleSession
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v2
        with: 
          registries: "705740530616"
      - name: STS Get Caller Identity
        run: aws sts get-caller-identity
      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: 705740530616.dkr.ecr.us-east-1.amazonaws.com
          REGISTRY_ALIAS: nd-github-actions-app
          REPOSITORY: ${{ inputs.repository }}
          IMAGE_TAG: ${{ inputs.branch }}
        run: |
          docker build -t $REPOSITORY:$IMAGE_TAG .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: Terraform Init
        run: terraform -chdir=./terraform init --backend-config=config/dev.config 
      - name: Terraform Workspace Select
        run: terraform -chdir=./terraform workspace select ${{ inputs.repository }}-${{ inputs.branch }} || terraform -chdir=./terraform workspace new ${{ inputs.repository}}-${{ inputs.branch }}
      - name: Terraform Plan
        run: terraform -chdir=./terraform plan -var environment=${{ inputs.branch }} -var repository=${{ inputs.repository }}
      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -var environment=${{ inputs.branch }} -var repository=${{ inputs.repository }} -auto-approve
